export type floaterObject = {
    icon: string,
    height: number,
    width: number,
    top: number,
    left: number,
    color: string,
    opacity: number,
    border: string,
    outline: string,
    boxshadow: string,
    horizontalDuration: number,
    horizontalDirection: "normal" | "reverse",
    verticalDuration: number,
    verticalDirection: "normal" | "reverse",
    spinDuration: number,
    pushLeftDuration: number,
    pushLeftForce: number,
    pushDownDuration: number,
    pushDownForce: number,
    rainbowDuration: number,
    growDuration: number,
    growScale: number,
    opacityDuration: number,
    opacityIntensity: number
}