export type floaterObject = {
    icon: string,
    height: number,
    width: number,
    top: number,
    left: number,
    color: string,
    opacity: number,
    border: string,
    outline: string,
    boxshadow: string,
    horizontalDuration: number,
    horizontalDirection: "normal" | "reverse",
    verticalDuration: number,
    verticalDirection: "normal" | "reverse",
    spinDuration: number,
    pushLeftDuration: number,
    pushLeftForce: number,
    pushDownDuration: number,
    pushDownForce: number,
    rainbowDuration: number,
    growDuration: number,
    growScale: number,
    opacityDuration: number,
    opacityIntensity: number
}

export default function newFloater(
    icon: string = "skull-crossbones",
    height: number = 0,
    width: number = 0,
    top: number = 0,
    left: number = 0,
    color: string = "",
    opacity: number = 100,
    border: string = "",
    outline: string = "",
    boxshadow: string = "",
    horizontalDuration: number = 0,
    horizontalDirection: "normal" | "reverse" = "normal",
    verticalDuration: number = 0,
    verticalDirection: "normal" | "reverse" = "normal",
    spinDuration: number = 0,
    pushLeftDuration: number = 0,
    pushLeftForce: number = 0,
    pushDownDuration: number = 0,
    pushDownForce: number = 0,
    rainbowDuration: number = 0,
    growDuration: number = 0,
    growScale: number = 0,
    opacityDuration: number = 0,
    opacityIntensity: number = 0
): floaterObject {
    return {
        icon: icon,
        height: height,
        width: width,
        top: top,
        left: left,
        color: color,
        opacity: opacity,
        border: border,
        outline: outline,
        boxshadow: boxshadow,
        horizontalDuration: horizontalDuration,
        horizontalDirection: horizontalDirection,
        verticalDuration: verticalDuration,
        verticalDirection: verticalDirection,
        spinDuration: spinDuration,
        pushLeftDuration: pushLeftDuration,
        pushLeftForce: pushLeftForce,
        pushDownDuration: pushDownDuration,
        pushDownForce: pushDownForce,
        rainbowDuration: rainbowDuration,
        growDuration: growDuration,
        growScale: growScale,
        opacityDuration: opacityDuration,
        opacityIntensity: opacityIntensity
    }
}

export function generateRandomFloater(icon:string, color: string, theme: "coder" | "beach" | "winter", windowWidth: number, windowHeight: number): floaterObject {
    const size = Math.max(Math.floor(Math.random() * 200), 75) 
    
    switch (theme) {
        case "beach":
            return newFloater(
                icon,
                size,
                size,
                Math.random() * windowHeight,
                0,
                color,
                Math.random() * (60 - 10) + 10,
                "",
                "",
                "",
                Math.random() * (12 - 3) + 3,
                Math.random() > .5 ? "normal" : "reverse",
                0,
                Math.random() > .5 ? "normal" : "reverse",
                0,
                Math.floor(Math.random() * 2),
                Math.floor(Math.random() * 50),
                Math.floor(Math.random() * 2),
                Math.floor(Math.random() * 50),
                0,
                Math.floor(Math.random() * 20),
                Math.max(Math.random() * 1.5, .5),
                Math.floor(Math.random() * 5),
                Math.max(Math.random() * 60, 10),
            )
        case "winter":
            return newFloater(
                icon,
                size,
                size,
                0,
                Math.random() * (windowWidth + 50) - 100,
                color,
                Math.random() * (60 - 10) + 10,
                "",
                "",
                "",
                0,
                Math.random() > .5 ? "normal" : "reverse",
                Math.random() * (15 - 3) + 3,
                "normal",
                Math.floor(Math.random() * 20),
                Math.floor(Math.random() * 2),
                Math.floor(Math.random() * 50),
                Math.floor(Math.random() * 2),
                Math.floor(Math.random() * 50),
                0,
                Math.floor(Math.random() * 20),
                Math.max(Math.random() * 1.5, .5),
                Math.floor(Math.random() * 5),
                Math.max(Math.random() * 60, 10),
            )
            
        default:
            return newFloater(
                icon,
                size,
                size,
                Math.max(Math.floor(Math.random() * 1000), 200),
                Math.max(Math.floor(Math.random() * 1000), 200),
                color,
                Math.max(Math.random() * 60, 10),
                "",
                "",
                "",
                Math.max(Math.random() * 10, 2),
                Math.random() > .5 ? "normal" : "reverse",
                Math.random() * (20 - 3) + 3,
                Math.random() > .5 ? "normal" : "reverse",
                Math.random() * (20 - 3) + 3,
                Math.floor(Math.random() * 2),
                Math.floor(Math.random() * 50),
                Math.floor(Math.random() * 2),
                Math.floor(Math.random() * 50),
                0,
                Math.floor(Math.random() * 20),
                Math.max(Math.random() * 1.5, .5),
                Math.floor(Math.random() * 5),
                Math.max(Math.random() * 60, 10),
            )
    }
    
}

